version: 0.9.0-{build}

environment:
  matrix:
    # node.js
    - nodejs_version: 0.12
    # io.js
    - iojs_version: 2
    # Previous versions
    - nodejs_version: 0.10
    - nodejs_version: 0.8
    # Previous versions of io.js
    - iojs_version: 1

platform:
  - x64
  - x86

install:
  # Install required version of Node.js/Io.js
  - ps: Install-Product node ($env:nodejs_version + $env:iojs_version) $env:platform
  # Update npm itself
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm install -g npm
  # Install dependencies
  - npm install

# Don't actually build
build: off

test_script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test

# Caching npm parts
cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules
